#!/bin/bash

# COLORS
Bold=$(tput bold)
Underline=$(tput sgr 0 1)
Reset=$(tput sgr0)
# Regular Colors
Red=$(tput setaf 1)
Green=$(tput setaf 2)
Yellow=$(tput setaf 3)
Blue=$(tput setaf 4)
Purple=$(tput setaf 5)
Cyan=$(tput setaf 6)
White=$(tput setaf 7)
# Bold
BRed=${Bold}${Red}
BGreen=${Bold}${Green}
BYellow=${Bold}${Yellow}
BBlue=${Bold}${Blue}
BPurple=${Bold}${Purple}
BCyan=${Bold}${Cyan}
BWhite=${Bold}${White}

Green="\e[0;32m\033[1m"
Red="\e[0;31m\033[1m"
Blue="\e[0;34m\033[1m"
Yellow="\e[0;33m\033[1m"
Cyan="\e[0;36m\033[1m"
Cyan1="\e[1;36m\033[1m"
Light="\e[96m\033[1m"
Gray="\e[0;37m\033[1m"
Purple="\033[0;35m"
fin="\e[0m"

# PROMPT
prompt1="Enter your option: "
prompt2="Enter n° of options (ex: 1 2 3 or 1-3): "
prompt3="You have to manually enter the following commands, then press ${BYellow}ctrl+d${Reset} or type ${BYellow}exit${Reset}:"

# Estilos
print_line(){
    printf "\e[1;34m%$(tput cols)s\n\e[0m"|tr ' ' '-'
}

print_line1(){
    printf "\e[1;34m%$(tput cols)s\n\e[0m"|tr ' ' '='
}

write_header(){
    clear
    print_line1
    echo -e "${Blue}# ARCHLINUX INSTALL${fin} ${Gray}$1${fin}"
    print_line1
    echo ""
}

print_info(){
    echo -e $"${Cyan1}$1${fin}\n"
}

pause_function(){
    echo
    print_line
    read -p "Presiona enter para continuar..."
}
#GLOBAL VARIABLES
checklist=(0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0)

mainmenu_item() {
	#if the task is done make sure we get the state
	if [ "$1" == 1 ] && [ "$3" != "" ]; then
		state="${BGreen}[${Reset}$3${BGreen}]${Reset}"
	fi
	echo -e "$(checkbox "$1") ${Bold}$2${Reset} ${state}"
}

checkbox() {
	#display [X] or [ ]
	[[ "$1" -eq 1 ]] && echo -e "${BBlue}[${Reset}${Bold}X${BBlue}]${Reset}" || echo -e "${BBlue}[ ${BBlue}]${Reset}"
}

read_input_options() {
	local line
	local packages
	if [[ $AUTOMATIC_MODE -eq 1 ]]; then
		array=("$1")
	else
		printf "%s" "$prompt2"
		read -r OPTION
		IFS=' ' read -r -a array <<<"${OPTION}"
	fi
	for line in "${array[@]/,/ }"; do
		if [[ ${line/-/} != "$line" ]]; then
			for ((i = ${line%-*}; i <= ${line#*-}; i++)); do
				packages+=("$i")
			done
		else
			packages+=("$line")
		fi
	done
	OPTIONS=("${packages[@]}")
}

AUI_DIR=$(pwd)                                                        #CURRENT DIRECTORY
[[ $1 == -v || $1 == --verbose ]] && VERBOSE_MODE=1 || VERBOSE_MODE=0 # VERBOSE MODE
LOG="${AUI_DIR}/$(basename "${0}").log"                               # LOG FILE
[[ -f $LOG ]] && rm -f "$LOG"